version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: test_php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basic_db
      MYSQL_USER: basic_dbu
      MYSQL_PASSWORD: E9x2W9c5
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - '8282:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: basic_dbu
      PMA_PASSWORD: E9x2W9c5